### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by ryleu**

### CODE REVIEW

**Comment by ryleu** [comment]
may close #16 @TristanMcGinnis

**Comment by ryleu** [comment]
closes #27

**Comment by Broken-Admin** [comment]
Need testing on basestation and rover comms. <3 Let's do that tonight.

**Comment by ryleu** [comment]
slow wifi threw a wrench in that plan. tomorrow night in a space with ethernet?

**Comment by ryleu** [comment]
tested working in theory. we still need a full integration test with the rover, but should be good to go after that

**Comment by ryleu** [comment]
build times are abysmal. may want to mount the development directory into the docker container instead

**Comment by ryleu** [comment]
closes #29

**Comment by ryleu** [comment]
closes #30

**Comment by ryleu** [comment]
readme `docker-compose` needs to change to `docker compose` to reflect modern docker versions

**Comment by ryleu** [comment]
with the development containers, it should close #32. requires testing.

**Pull request merged**
